import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/logo3.png"/>
      </head>
      <body>
        {/* <Navbar /> */}
        <div class="container">
          {/* <Sidebar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
